/**
 * Buzzword Detection Data — Single Source of Truth
 * 
 * Shared between BuzzwordPanel (contextual replacements)
 * and HUD (severity metrics). Import from here to prevent
 * the two lists from drifting out of sync.
 */

// ============================================================================
// Buzzword Alternatives (used by BuzzwordPanel for replacement suggestions)
// ============================================================================

export const BUZZWORD_ALTERNATIVES: Record<string, string[]> = {
  'leverage': ['use', 'apply', 'take advantage of', 'work with'],
  'leveraging': ['using', 'applying', 'working with'],
  'leveraged': ['used', 'applied', 'worked with'],
  'utilize': ['use', 'apply', 'employ'],
  'utilizes': ['uses', 'applies'],
  'utilizing': ['using', 'applying'],
  'utilization': ['use', 'usage'],
  'seamless': ['smooth', 'easy', 'simple', 'effortless'],
  'seamlessly': ['smoothly', 'easily', 'simply'],
  'cutting-edge': ['modern', 'advanced', 'new', 'latest'],
  'cutting edge': ['modern', 'advanced', 'new', 'latest'],
  'revolutionize': ['transform', 'change', 'improve', 'redesign'],
  'revolutionary': ['transformative', 'new', 'groundbreaking'],
  'revolutionizing': ['transforming', 'changing', 'improving'],
  'unlock': ['enable', 'reveal', 'access', 'discover'],
  'unlocking': ['enabling', 'revealing', 'accessing'],
  'unlocks': ['enables', 'reveals', 'accesses'],
  'empower': ['enable', 'help', 'allow', 'support'],
  'empowering': ['enabling', 'helping', 'supporting'],
  'empowered': ['enabled', 'helped', 'supported'],
  'empowerment': ['enablement', 'support', 'capability'],
  'robust': ['strong', 'reliable', 'solid', 'stable'],
  'robustness': ['strength', 'reliability', 'stability'],
  'synergy': ['cooperation', 'teamwork', 'collaboration'],
  'synergize': ['collaborate', 'work together', 'combine'],
  'synergistic': ['collaborative', 'cooperative', 'combined'],
  'optimize': ['improve', 'enhance', 'refine', 'better'],
  'optimization': ['improvement', 'enhancement'],
  'optimizing': ['improving', 'enhancing', 'refining'],
  'optimized': ['improved', 'enhanced', 'refined'],
  'streamline': ['simplify', 'improve', 'speed up', 'ease'],
  'streamlined': ['simplified', 'improved', 'easier'],
  'streamlining': ['simplifying', 'improving', 'easing'],
  'innovative': ['new', 'creative', 'original', 'fresh'],
  'innovation': ['creativity', 'new idea', 'invention'],
  'innovate': ['create', 'invent', 'improve'],
  'next-generation': ['new', 'modern', 'advanced', 'updated'],
  'next generation': ['new', 'modern', 'advanced', 'updated'],
  'state-of-the-art': ['advanced', 'modern', 'latest', 'best available'],
  'state of the art': ['advanced', 'modern', 'latest', 'best available'],
  'game-changing': ['important', 'transformative', 'significant'],
  'game changer': ['big change', 'major improvement', 'breakthrough'],
  'best-in-class': ['excellent', 'top-quality', 'leading', 'superior'],
  'best in class': ['excellent', 'top-quality', 'leading', 'superior'],
  'world-class': ['excellent', 'outstanding', 'top-tier', 'high-quality'],
  'world class': ['excellent', 'outstanding', 'top-tier', 'high-quality'],
  'industry-leading': ['leading', 'top', 'best', 'pioneering'],
  'industry leading': ['leading', 'top', 'best', 'pioneering'],
  'paradigm shift': ['major change', 'big shift', 'fundamental change'],
  'paradigm-shifting': ['transformative', 'groundbreaking', 'revolutionary'],
  'disruptive': ['innovative', 'game-changing', 'transformative'],
  'disruption': ['change', 'innovation', 'transformation'],
  'disrupt': ['change', 'challenge', 'transform'],
  'transformative': ['significant', 'important', 'life-changing'],
  'transform': ['change', 'improve', 'convert', 'reshape'],
  'transformation': ['change', 'shift', 'evolution'],
  'holistic': ['complete', 'comprehensive', 'whole', 'full'],
  'holistically': ['completely', 'fully', 'entirely'],
  'comprehensive': ['complete', 'thorough', 'full', 'detailed'],
  'strategic': ['planned', 'deliberate', 'intentional', 'thoughtful'],
  'strategically': ['deliberately', 'intentionally', 'carefully'],
  'mission-critical': ['essential', 'vital', 'crucial', 'necessary'],
  'mission critical': ['essential', 'vital', 'crucial', 'necessary'],
  'actionable': ['practical', 'useful', 'concrete', 'specific'],
  'actionability': ['usefulness', 'practicality'],
  'scalable': ['expandable', 'flexible', 'adaptable', 'growing'],
  'scalability': ['flexibility', 'adaptability', 'growth potential'],
  'scale': ['grow', 'expand', 'increase'],
  'agile': ['flexible', 'adaptable', 'quick', 'responsive'],
  'agility': ['flexibility', 'adaptability', 'speed'],
  'dynamic': ['active', 'changing', 'flexible', 'responsive'],
  'dynamically': ['actively', 'flexibly', 'responsively'],
  'proactive': ['forward-thinking', 'preventive', 'anticipatory'],
  'proactively': ['in advance', 'ahead of time', 'preventively'],
  'end-to-end': ['complete', 'full', 'comprehensive'],
  'end to end': ['complete', 'full', 'comprehensive'],
  'turnkey': ['ready-made', 'complete', 'ready to use'],
  'turn-key': ['ready-made', 'complete', 'ready to use'],
  'bleeding-edge': ['very new', 'experimental', 'latest'],
  'bleeding edge': ['very new', 'experimental', 'latest'],
  'deep dive': ['detailed analysis', 'thorough look', 'close examination'],
  'deep-dive': ['detailed analysis', 'thorough look', 'close examination'],
  'circle back': ['follow up', 'return to', 'revisit', 'get back to'],
  'touch base': ['check in', 'talk', 'connect', 'follow up'],
  'move the needle': ['make progress', 'improve', 'make a difference'],
  'low-hanging fruit': ['easy wins', 'quick wins', 'easy opportunities'],
  'think outside the box': ['be creative', 'think differently', 'innovate'],
};

// ============================================================================
// Flat Term List (used by HUD for quick regex matching)
// Derived from alternatives + extra corporate jargon without replacements
// ============================================================================

/** 
 * Comprehensive list of buzzwords/jargon for detection. 
 * Includes all keys from BUZZWORD_ALTERNATIVES plus additional
 * corporate terms that the HUD should flag. 
 */
export const GENERIC_TERMS: string[] = [
  // All terms with alternatives
  ...Object.keys(BUZZWORD_ALTERNATIVES),

  // Additional corporate jargon (HUD flags these; BuzzwordPanel may not have replacements)
  'next-gen',
  'ai-powered',
  'ai powered',
  'ml-driven',
  'unlock the power',
  'synergies',
  'innovating',
  'gamechanger',
  'market-leading',
  'new paradigm',
  'disrupting',
  'transforming',
  '360-degree',
  '360 degree',
  'strategic alignment',
  'business-critical',
  'actionable insights',
  'at scale',
  'e2e',
  'out-of-the-box',
  'loop back',
  'reach out',
  'moving the needle',
  'take it offline',
  'take this offline',
  'boil the ocean',
  'drink the kool-aid',
  'bandwidth',
  'no bandwidth',
  'pivot',
  'pivoting',
  'double-click',
  'double click on that',
  'unpack',
  'let me unpack',
  'net-net',
  'net net',
  'learnings',
  'key learnings',
  'value-add',
  'value add',
  'added value',
  'ecosystem',
  'digital ecosystem',
  'omnichannel',
  'omni-channel',
  'customer-centric',
  'user-centric',
  'data-driven',
  'insight-driven',
  'future-proof',
  'future proof',
];
